### ISSUE TITLE
Feedback for “Reverse Proxy with Basic Authentication”

### ISSUE THREAD

**Issue by kght6123** [LibreChat-AI/librechat.ai#111]
I recently needed the following additional settings for Nginx.

One is to exclude Basic Authentication for manifest.

```
        location /manifest.webmanifest {
            auth_basic off;
            proxy_pass http://127.0.0.1:3080;
        }
```

The second is to exclude Basic authentication from the health check required when using the Cloudflare registrar.

```
        location /health {
            auth_basic off;
            proxy_pass http://127.0.0.1:3080;
        }
```

Without this, Safari and Chrome will repeatedly request credentials.
Safari in particular is difficult to use on iPads, iPhones, Macs, etc., as previous Safari bugs prevented access to sites and require Basic credentials to be entered each time a site is saved.

Some of the issues are specific to Cloudflare and Safari but took a while to resolve,
Please add them to the documentation if you like.

**Comment by fuegovic** [comment]
You are welcome to submit a pull request for this; you can do so easily by clicking on 'Edit this page on GitHub' located at the bottom of the right-hand sidebar.
![image](https://github.com/user-attachments/assets/fe015b11-9994-443c-aec8-c7860a81dabd)

**Comment by kght6123** [comment]
@fuegovic 
Created PR. Please confirm.
https://github.com/LibreChat-AI/librechat.ai/pull/117
