### ISSUE TITLE
Feedback for “Tools and Plugins”

### ISSUE THREAD

**Issue by ThreepE0** [LibreChat-AI/librechat.ai#121]
I've got a plugin working that calls functions, but I'm wondering how I can move it over to tools from functions, as functions are deprecated and are conflicting with some of my other services.  

I don't see a way to have a "plugins" client that uses a specific endpoint either, is there one?

**Comment by fuegovic** [comment]
plugins will be deprecated soon in favor of "Agents"

**Comment by ThreepE0** [comment]
> plugins will be deprecated soon in favor of "Agents"

A month later, and a reply that simply fails to understand that agents are an entirely different thing. I've written my own OpenAi proxy to get around this in the last month so I don't care anymore.  My solution works for agents, completions, and chat, but with so many web UIs available, I'd have liked to see a bit more of a solid direction and some actual communication from this repo.
