### ISSUE TITLE
Feedback for “HuggingFace”

### ISSUE THREAD

**Issue by Deadlywolf712** [LibreChat-AI/librechat.ai#152]
MONGO_URI

Please, i don't know what this means.

It just says * use the string aquired in the previous step.

it's so unclear i'm getting frustred.

**Comment by fuegovic** [comment]
Sorry about that, the info was indeed missing. Will fix soon. This is how you get the `MONGO_URI` : https://librechat.ai/docs/configuration/mongodb/mongodb_atlas
