### ISSUE TITLE
Found broken `/docs` link. Please fix!

### ISSUE THREAD

**Issue by shrijit-narkar** [LibreChat-AI/librechat.ai#22]
https://www.librechat.ai/blog/ai_endpoints - This link which is specified in https://www.librechat.ai/blog/2023-11-30_litellm#3-configure-librechat is giving 404

**Comment by spinagon** [comment]
Should probably point here https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints instead

**Comment by fuegovic** [comment]
will fix very soon, thanks for reporting this
