### ISSUE TITLE
Found broken `/docs` link. Please fix!

### ISSUE THREAD

**Issue by Bigrizzm888** [LibreChat-AI/librechat.ai#56]
I was trying to help the gentleman trying to fix his code take a look at the answer code that he has and got a 404 error and I don't appreciate a 404 in this situation on this website and this platform thank you

**Comment by fuegovic** [comment]
Can you please tell us what was the problematic URL / where was the broken link?

**Comment by fuegovic** [comment]
will re-open if the broken link is shared
