### ISSUE TITLE
Broken link: password reset

### ISSUE THREAD

**Issue by OverLordGoldDragon** [LibreChat-AI/librechat.ai#62]
From latest `main` in `LibreChat`

https://www.librechat.ai/docs/configuration/authentication/password_reset

![image](https://github.com/LibreChat-AI/librechat.ai/assets/16495490/2dcfaa9a-c5ef-448b-a4f1-6a0bc7860af9)

Seems to be this now https://www.librechat.ai/docs/user_guides/password_reset

**Comment by berry-13** [comment]
thank you!
